Netflix-Skunkworks/iep-apps

- build.sbt
- iep-archaius/README.md
- iep-archaius/src/main/resources/application.conf
- iep-archaius/src/main/resources/log4j2.xml
- iep-archaius/src/main/scala/com/netflix/iep/archaius/DynamoService.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/Main.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesApi.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesContext.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesLoader.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/package.scala
- iep-archaius/src/test/scala/com/netflix/iep/archaius/MockDynamoDB.scala
- iep-archaius/src/test/scala/com/netflix/iep/archaius/PropertiesApiSuite.scala
- iep-archaius/src/test/scala/com/netflix/iep/archaius/PropertiesLoaderSuite.scala
- project/Dependencies.scala
This is a simple property service backed by a DynamoDB table
that can be used with `iep-module-archaius2`. This service
currently only supports the read operations. Writes are
managed by a deployment service internally.
> add initial version of simple property service

- build.sbt
- iep-atlas/README.md
- iep-atlas/src/main/resources/eureka-client.properties
Add sample eureka config for running locally with no
Eureka server and link to config page for users to
configure for their own eureka service.
> add sample eureka configuration

- iep-lwc-bridge/src/main/resources/application.conf
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/UpdateApi.scala
Adds another endpoint used internally to some parts of
the stack. Makes it easier for us to plug in the bridge
at various places.
> add another backwards compatibility endpoint

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
The request was always getting sent before, now it
will only be sent if there is some metrics data.
> do not send to lwc if payload is empty

- iep-lwc-bridge/src/main/resources/application.conf
Since this is not a sharded storage layer that will
keep the values for a long time, there is no need
to intern the strings and tag maps and it adds a
lot of overhead while processing.
> do not intern the values while parsing

- build.sbt
The Atlas webapi is not needed for this app.
> remove unnecessary dependency for iep-archaius

- build.sbt
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
Intead of using one group for the evaluator, split the
expressions into groups based on the app. This should
significantly reduce the number of expressions that need
to get checked for a datapoint as it is flowing through
the system.
> split expressions into groups based on the app

- build.sbt
- iep-lwc-cloudwatch/README.md
- iep-lwc-cloudwatch/src/main/resources/application.conf
- iep-lwc-cloudwatch/src/main/resources/log4j2.xml
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/AppModule.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ConfigManager.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/Main.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
- project/Dependencies.scala
This is a simple experimental app that receives configs
from ConfigBin, evaluates the expressions using LWC, and
then forwards the results to CloudWatch. The use-case is
to drive auto-scaling policies based on custom metrics.
> app to send LWC eval results to CloudWatch

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Moved to the source to ensure that the flow doesn't stop
and cause the overall stream to fail.
> fix the recovery for cloudwatch put

- iep-lwc-bridge/src/main/resources/application.conf
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/AppModule.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/Main.scala
Splits out the expression update to a separate actor and
switches the publish actor to use a round robin dispatcher.
> move expr updates to separate actor

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- project/Dependencies.scala
When passing the tags to the evaluator it will end up
doing a lot of get and contains calls on the java map.
The custom wrapper is more efficient for those use-cases
and avoids the object allocation.
> use SmallHashMap.asJavaMap

- atlas-stream/src/main/resources/application.conf
- atlas-stream/src/main/scala/com/netflix/atlas/stream/Main.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
- build.sbt
This app provides a single endpoint `/stream` that takes
and atlas URI as the rest of the path. For example:
```
/stream/http://atlas/api/v1/graph?q=name,rps,:sum
```
> add minimal example app to stream from lwc

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
To make sure there aren't any timeouts when running
using a larger step size, this change will output a
heartbeat message every 5 seconds.
> add heartbeats to ensure frequent traffic

- project/BuildSettings.scala
Adds the build time and commit into the manifest for the
jar file to aide in debugging.
> additional build metadata for jar file

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
Before it was just doing it once and the brower doesn't
seem to like it. Doubled it up and tested with javacript
EventSource:
```html
<html>
<head>
<title>SSE test</title>
</head>
<body>
<pre id="content"></pre>
<script>
var uri = "http://localhost:7101/stream/http://localhost:7001/api/v1/graph?q=name,ssCpu,:re,:avg,(,name,),:by";
var source = new EventSource(uri);
source.onmessage = function(event) {
document.getElementById("content").innerHTML += event.data + "\n";
};
</script>
</body>
</html>
```
> fix ending to use CRLFCRLF

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
To reduce the number of put calls, the sends to CloudWatch
are batched. The downside is that if a value is invalid, then
the whole batch gets rejected. In particular, we were seeing
NaN values cause the batch to fail with:
```
com.amazonaws.services.cloudwatch.model.InvalidParameterValueException:
The value ? for parameter MetricData.member.1.Value is invalid.
(Service: AmazonCloudWatch; Status Code: 400;
Error Code: InvalidParameterValue; Request ID: XYZ)
```
This change adds a truncate step that coerces the value to
fit the CloudWatch restrictions. The truncation logic was
borrowed from the Servo library and has been used for many
years in that library.
> adjust values to fit CloudWatch restrictions

- build.sbt
- iep-clienttest/README.md
- iep-clienttest/src/main/resources/application.conf
- iep-clienttest/src/main/resources/log4j2.xml
- iep-clienttest/src/main/scala/com/netflix/iep/clienttest/InstrumentationService.scala
- iep-clienttest/src/main/scala/com/netflix/iep/clienttest/Main.scala
- iep-clienttest/src/main/scala/com/netflix/iep/clienttest/MetricLibrary.scala
- project/Dependencies.scala
This is a simple application for testing the overhead
of the client. It creates a configurable number of metrics
of various types. The immediate use-case is to look into
some slowdowns we are seeing in collecting metrics due
to meltdown remediations.
> add client test app

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/package.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
Refactors the expression evaluation for the LWC bridge
to levarage the Atlas query index. Before it was only
segmenting by application. If a larger portion of the
queries due not have an exact match on application,
cluster, or asg, then we cannot extract an application
and they would get placed in the catch all bucket.
Expressions in the catch all must be checked against
all datapoints flowing through the system.
With the query index we can drill down based on any
equal clauses in the query. For the actual data set
that was causing problems there are 18.5k expressions
and 2500 were in the catch all bucket. Using the query
index that top-level fallback set reduced to 46. As
a further optimization we are now ignoring those top-level
fallbacks from the index and requiring the user to be
more …
> use QueryIndex for LWC bridge

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
We use the `nf.datasource` tag to specify the Druid
datasource and the `name` to match a metric for that
datasource. When searching for the list of values for
a given dimension, we need to ensure those aspects of
the Atlas query are removed before converting the
remainder of the query to a Druid filter.
> fix filtering for druid tag queries

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
When fetching the data form Druid the query was being
used to select the datasource and name, but was ignored
after that. Now it is converted to a filter and passed
to the group by request that is sent to Druid.
> pass query in as filter to druid group by

- atlas-aggregator/README.md
- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/resources/log4j2.xml
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/Main.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AppModuleSuite.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
- build.sbt
- project/Dependencies.scala
This is an initial prototype for an aggregator service
to receive deltas from stateless clients. The api is
similar to internal aggregator that has been used for
a while to perform inline removal of the node dimension.
In this case updates are forwarded to an AtlasRegistry
so it will behave like a normal client on behalf of
the clients.
For more details see Netflix/spectator#432.
Left as future work:
- Reduce the expiration period for the Atlas registry.
This will require changes on the Spectator side to
improve the cleanup.
- Minimal validation of datapoints. In particular checks
for tag length and number of tags should be performed.
- Automatic rollup based on cardinality or churn. This
is to protect the backends and avoid explosion of metrics
volume if improper tagging is used. In …
> initial version of aggregator service

- iep-lwc-cloudwatch/src/main/resources/application.conf
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Though we generally try to keep the data flow regionally
isolated, there are some use-cases where we need the data
from one region in another. Current example is reservation
data tracked from a centrallized tool that needs to be
used for auto-scaling in various regions.
> add support for publishing to CW cross-region

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AppModuleSuite.scala
The AggrConfig was only applying the prefix when checking
if the key exists not when reading it. This would fail with
a missing config key exception for any key that was actually
set.
> use prefix when accessing config settings

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
Otherwise we get multiple copies and the one being updated
is not the one that was started.
> specify the registry as a singleton

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
An explicitly specified tag limit was getting used when
mapped to a druid search query, but not for the special
name and nf.datasource dimensions.
> honor limit for name and nf.datasource dimension

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
The field should be `pattern` and not `value`.
> fix field name for regex filter

- atlas-druid/src/main/resources/application.conf
Increase the max number of allowed requests and
connections to permit more concurrent requests.
> adjust druid client settings

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
Uses the filtering dimension spec where possible to have
druid filter out the result set on the server side. We
still to the local filtering for cases where the list or
regex filter specs do not match the query intent.
> server side filter for multi-value dimensions

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Adds an option to control the amount of time used when
performing searchs for the tags api. Before it was fixed
to 14 days. That can cause a lot of load on druid for
high cardinality dimensions.
> add config option for tag query interval

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
If a single data expression mapped to multiple druid
queries, then it would just take the first result. Now
it will properly merge those results and evaluate the
data expression on the combined set.
This fixes #50.
> fix combining results across druid queries

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
In this case the query has already been checked by
the index. It doesn't need to be rechecked when
creating the aggregator instance.
> avoid checking the query again

- iep-lwc-bridge/src/main/resources/application.conf
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/StatsApi.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/StatsApiSuite.scala
This is mostly to help with debugging so we can quickly
verify if we are receiving data for a given expression
and how much data we are seeing for it.
> add basic stats endpoint for expressions

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
These will be long-lived connections and when behind a load
balancer. AWS ELBs will wait for a long time after the client
goes away hoping the request will complete and it can reuse
the connection. In this case the stream will never complete.
Setting connection close should let the load balancer know it
can give up on the connection without waiting.
> disable connection reuse for stream endpoint

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
Fixes:
```
1) Could not find a suitable constructor in com.netflix.iep.lwc.ExprUpdateService.
Classes must have either one (and only one) constructor annotated with @Inject
or a zero-argument constructor that is not private.
at com.netflix.iep.lwc.ExprUpdateService.class(ExprUpdateService.scala:52)
at com.netflix.iep.lwc.AppModule.configure(AppModule.scala:27)
```
> add inject annotation to expr updater

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
In one of our clusters we saw the stream get shutdown when
the configbin service initiated a failover.
> ensure stream is restarted for unexpected failures

- iep-lwc-bridge/src/main/resources/application.conf
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/AppModule.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/StatsApiSuite.scala
This would be used for more fine grained debugging of a
particular subscription id without all the noise of logging
all of the datapoints flowing through.
> add option to log values for a subscription

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Makes it easier to detect if there is no data going out
to cloudwatch for a prolonged period of time.
> add gauge tracking time since last put

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesApi.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/StatsApi.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/UpdateApi.scala
- project/Dependencies.scala
This will allow the endpoint to get configured correctly
for the common-ipc metrics.
> use endpoint path directives

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/package.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
- project/Dependencies.scala
Expensive expressions that are being rejected will now be
indicated to the user with an explicit error message.
> forward errors to lwcapi for rejected expressions

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenService.scala
- iep-lwc-loadgen/src/test/scala/com/netflix/iep/loadgen/LoadGenServiceSuite.scala
When extracting the step it would crash before if there was
an invalid uri. Now it will fallback to the default step and
let the eval library handle the invalid uris passed in as part
of the set of data sources.
> avoid crashing if invalid uri is used in config

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenService.scala
Last put time gauge was copy and paste from cloudwatch
forwarder that was used as the initial template.
> fix unused variable warning

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenService.scala
Use the same value as the type field in the messages coming
back to the user for the `msgType` dimension on the metric.
> update msgType tag to match type field in messages

- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/AppModule.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/NotificationLogger.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesNotificationLogger.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
Guice injection does not recognize the default fifth parameter of
`SesMonitoringService`. I created a trait and a default implementation
for an `@Provider` in the `AppModule`, while still enabling tests to
provide a spy implementation.
> Fix Guice injection issue

- iep-ses-monitor/src/main/resources/log4j2.xml
With the introduction of the NotificationLogger trait and default
implementation, I updated the name of the logger to match the package
structure. Update the log4j.xml configuration.
> Update SesNotification logger name

- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
I had initially thought I would pass the `Message` portion of the
notification, but that didn't turn out to be the case. In the meantime,
that incorrect assumption was encoded into the tests.
This commit makes the structure of the test messages match what is seen
in the live service and fixes the logic that extracts information for
Atlas metrics.
> Fix notification structure

- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenService.scala
Changes lwc loadgen to run one evaluator per group of
expressions. This more closely simulates the behavior
of internal usage.
> partition the expressions for loadgen

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
The client should not send values that are NaN, but if it
does occur go head and drop them here before the evaluate
step. This avoid spurious NaN lines showing up in the
streaming output.
> ignore datapoints with a value of NaN

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
The default limit is 8m and we have exceeded that in some
environments. Also, the current behavior seems to be it will
hang the stream with no clear error if this size is exceeded.
So for now we'll remove the size limit so at least the failure
mode will be more obvious.
>  avoid entity size limit for fetch expressions

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
OR clauses can result in multiple values and need to be
included in the group by result similar to IN or regex.
> druid: improve handling of OR queries

- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesLoader.scala
For test cases having an initial delay of `0.seconds` can
cause the automatic tick to come through at the wrong time
and cause spurious test failures.
> increase initial delay for properties loader

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
This context isn't provided when there is a failure
due to access denied for the AssumeRole.
> log region/account for failed requests

- build.sbt
- iep-archaius/src/main/scala/com/netflix/iep/archaius/Main.scala
Update iep-archaius to use the helper factory so that
the client can be configured via the config files in
a manner consistent with our other applications.
> use AwsClientFactory to create DynamoDB client

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/resources/segmentMetadataResponse.json
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
Switches to using segmentMetadata queries for understanding
the set of dimensions and metrics for a given data source.
This has two benefits: 1) it seems to be more reliable as
in some error cases the GET request to /datasources doesn't
show any dimensions, and 2) it gives us type information
that can be used to make a more informed choice about how
to query the data.
The main downside is that segmentMetadata seems to be quite
a bit more expensive to compute. The intervals are limited
to the tag query interval for now which seems to keep the
overhead to a reasonable level.
> use segmentMetadata for describing data sources

- iep-ses-monitor/src/main/resources/application.conf
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
There have been occasional, transient DNS blips resulting in an
`UnknownHostException` communicating with the SQS host. This currently
causes the stream to fail permanently, since the stream restart logic
can't retrieve the queue URI until the DNS name starts resolving
again.
This commit adds retries for retrieving the queue URI on
`UnknownHostException`, and a metric for queue URI retrieval failure.
> Add retry for UnknownHostException

- iep-lwc-cloudwatch-model/src/main/scala/com/netflix/iep/lwc/fwd/cw/ConfigBinVersion.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-fwding-admin/src/main/resources/application.conf
- iep-lwc-fwding-admin/src/main/resources/cw-fwding-cfg-schema.json
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Api.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/AppModule.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDao.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Purger.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ApiSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDaoSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDaoTestImpl.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/PurgerSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/SchemaValidationSuite.scala
Adds an endpoint to update or remove cluster configurations
in ConfigBin for the given expressions.
Modified the cluster config schema to allow empty list
for `checksToSkip` field. This is convenient because Json
encoding creates this empty list.
Moved ConfigBinVersion to the shared library.
> Add endpoint for removing purge eligible expressions

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/test/resources/groupByResponse.json
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
Druid treats null and empty string as being the same. If
dimensions returned as part of the event map from a group
by request have a null value, then filter them out to avoid
NPE during request processing in Atlas. For the Atlas storage
null values are not allowed and cannot be part of the response.
> druid: filter out datapoints with null values

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
Fixes the interpretation of has queries to more closely match
the expectations of the Atlas construct:
1. If the dimension is not present on a given datasource it
will now be handled via a query simplification and never
get sent to druid. This will allow queries that look for
`not(has(k))` to work if `k` is not present.
2. When the dimension is present, a has query will now get
written as `not(k == "")`. Druid treats empty strings and
null values as being the same so this is matching for
entries where the value for the key is not null. Before
it would check for the key and have a javascript function
that always returned true. That would match entries that
were null which is not expected by the user.
> druid: improve behavior of has queries

- atlas-slotting/src/main/resources/application.conf
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/DynamoOps.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingService.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Util.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/DynamoOpsSuite.scala
The required DynamoDB capacity can differ based on account and region,
depending on the number and size of ASGs being tracked. This change
provides the ability to specify the desired read and write capacity per
account and region, with a default value as the fallback.
The timestamp update and deactivate ASG methods do not change the data
payload in DynamoDB, so the condition expressions have been updated to
check the data that is changing. the data payloads can be up to 400KB in
size, while a Boolean and a Long are just a few bytes. this should help
save some DynamoDB write capacity. keeping the conditional checks in
place will provide stability for the items, when there are multiple
writers during a deployment.
> DynamoDB Capacity Updates

- atlas-slotting/src/scripts/compare-data.py
This script is used to verify that slots are consistent for a given
set of ASGs in the Atlas Slotting service and Edda.
> slotting: add compare-data script

- build.sbt
- iep-lwc-fwding-admin/src/main/resources/application.conf
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/AppModule.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDao.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/MarkerService.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Purger.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPolicies.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesDao.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDaoSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/MarkerServiceSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/PurgerSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesDaoSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesTestImpl.scala
Query Edda to determine whether a scaling policy is
created in Ec2 or Titus for the metric that is forwarded
to CW.
> Scaling policy lookup for expressions

- iep-ses-monitor/src/main/resources/log4j2.xml
Log messages need to be separated by a new line.
> Add new line to SES notification log pattern

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
Removes the `cardinality` and `size` analysis types from
the default list for segment metadata. These types can
cause a lot of overhead for the query.
> druid: simplify default analysis types

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AppModuleSuite.scala
- project/Dependencies.scala
See Netflix/spectator#708. This will allow the aggr registry
metrics to be reported for the aggregator cluster instead of
getting forwarded to the target account.
> update aggregator to use debugRegistry

- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/DynamoOps.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Grouping.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingCache.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingService.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/GroupingSuite.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/SlottingApiSuite.scala
- Switch the cache to use a SortedMap, so the output will be sorted by ASG name
- Log the DynamoDB table being used at startup
- Add details to the message when SlottedAsgDetails fails the requirement
> Sort API Output

- atlas-slotting/src/main/resources/application.conf
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingApi.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/SlottingApiSuite.scala
- build.sbt
- project/Dependencies.scala
This service is polled heavily by many nodes and the responses
are typically the same. The most expensive aspects currently
are compressing the payloads followed by converting the objects
to JSON. This change should considerably reduce both.
> enable response caching for slotting service

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
The LWC bridge will now filter the expressions to only those
that match the primary step size for the corresponding Atlas
backend.
> restrict exprs for bridge to primary step

- build.sbt
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/AppModule.scala
- project/Dependencies.scala
No async client was available in the factory for the AWS 1.x SDK and,
since the SES Monitor usage was a one-off, I didn't add it. Now that
alpakka-sqs uses the AWS 2.x SDK and there is a client factory for that
available, I'm moving the SES Monitor to leverage it.
> Migrate to iep.aws2.AtlasClientFactory

- iep-lwc-cloudwatch-model/src/main/scala/com/netflix/iep/lwc/fwd/cw/Report.scala
- iep-lwc-fwding-admin/src/main/resources/application.conf
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDao.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/MarkerService.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPolicies.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Timer.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDaoSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/MarkerServiceExprDetailsSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/MarkerServiceSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/TimerSuite.scala
Save the report timestamp for every forwarded metric and use it
to remove the entry when the metric is no longer reported.
This is useful to keep the list size bounded for the forwarded metrics
and scaling policies in a 'ExpressionDetails' admin record.
When one expression is used to forward metrics for many asgs,
the admin record should be updated when the asgs are removed and
not forwarding any data.
> Purge the forwarded metrics admin record that are no longer reported

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
It will now work for clauses that look for a specific
value in addition to a null value. For example:
```
foo,bar,:eq,foo,:has,:not,:or
```
> druid: improve dimension spec mapping

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
Updates the aggregator to fix invalid characters in the
strings while the data is being parsed. This has a few
advantages:
1. Reduces cost for serializing later when publishing.
2. Dedupes the strings as they are coming in to reduce
the overall memory footprint.
> fix invalid characters while parsing

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/resources/application.conf
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
Before this would get done for all metric with a commonTags
config. Now we can omit this from gauges as the max behavior
will choose the correct value. For now to avoid deduping this
tag is still needed on counters.
> add aggr tag explicitly to counters

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
These will get applied more narrowly now as it is only
needed for counters and not gauges.
> remove common tags from aggr registry

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
Before these would be empty because druid would return the
event with a `"key": null` and it would get filtered out.
The filtering was added to avoid NPE with percentile queries.
This changes it to filter the keys with null values from the
set of tags rather than the overall datapoint. Checking with
a percentile query, this does not regress that behavior.
> druid: fix `key,:has,:not` queries

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Update the druid group by queries to filter out zero
values on the server. For some percentile queries this
reduces the response size considerably.
> druid: filter out 0 values server side

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
For some OR clauses this is needed to preserve the tag
information for the eval step. Otherwise the data would
get filtered out and result in an empty graph.
> druid: extract tags from simplified query

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/ExplainApi.scala
Adds a helper that can be used to get an overview of the
druid queries that will be executed for a given Atlas
expression.
> druid: add explain endpoint for graph queries

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/ForeachApi.scala
This provides compatibility with some internal tools that
still use this legacy api. It should ideally get phased out
over time, but for now this should unblock those use-cases.
> druid: add legacy foreach api

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
The change in #170 would cause not queries to get simplified
to false and incorrectly match nothing. The exact matching
criteria has been updated to match the behavior of exactKeys.
> druid: fix matching of not clauses

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
For the counters used to compute the percentile approximations,
automatically rollup nf.node and nf.task if present. These
should always get rolled up as soon as possible.
> rollup nf.node for percentile counters

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- project/Dependencies.scala
Gives the aggregator more time to send data when handling
many metrics.
> set initial delay to start of interval

- build.sbt
- project/Dependencies.scala
`iep-ses-monitor` now uses the AWS v2 SDK. This will restore metrics for
the AWS calls it makes.
> Add dependency on spectator-ext-aws2

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/FailureMessage.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
The `/update` endpoint on the aggregator will now validate
the datapoints and indicate any issues in the response. This
can be used by thin clients to inform the user of problems.
The rules are mostly the same as those used for the publish
endpoint of the backend. Valid characters are not checked
because they will get fixed on this path by the registry.
> validate datapoints coming into the aggregator

- build.sbt
- project/Dependencies.scala
Pick up fix for DNS resolution with netty client. Also
fixes the explicit SQS dependency for the SES monitor
to use the V2 SDK instead of V1.
https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#21056-2020-01-24
> aws-sdk-java-v2 2.10.56

- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalFlow.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
Currently, when EvalService restarts for any error, it completes queues for all active sessions, and because EvalFlow pushes out a new Source continuously whenever previous one completes, and the initial heartbeat is always available immediately, which may cause super high cpu/network consumption at both client and server side.
The fix is to have EvalFlow only push out Source once and simply completeStage if it ever gets pulled again due to completion of previous source. This means all active session will be closed on EvalService restart, which I think should be the right thing to do.
Also add some comments about why not doing synchronization between `cleanup` and `register` on EvalService restart.
> stop all sessions on EvalService restart

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/Aggregator.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AtlasAggregatorService.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/package.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
This makes it easier to reuse with different policies for
validation and rollups. For some future work with sharding
the aggregator data this should be useful to have different
policies after processing the initial payload from the user.
> aggr: move decoding logic to helper class

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
These get emitted after it is done emitting all configs
for the first time on a sync request.
> add counter for done messages from configbin

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Track the repo version from the heartbeat messages. This
can be used for debugging if necessary to see how long it
took for a given change to propagate to the client.
> add gauge for configbin repo version

- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
atlas-stream: add a metric to track number of DataSource's in EvalSerice
> atlas-stream: add a metric to track number of DataSource's

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
iep-lwc-loadgen: allow specifying uri start and end index for better control over what uris to use.
> iep-lwc-loadgen: allow specifying uri start and end index

- iep-lwc-fwding-admin/src/main/resources/cw-fwding-cfg-schema.json
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/SchemaValidationSuite.scala
Allow whitespace in the metricName used for CW metric
> CW forwading config schema update

- .travis.yml
- project/Dependencies.scala
Internally all uses of these have moved to scala 2.13. To
reduce maintenance effort, drop 2.12 builds.
> stop cross building for scala 2.12

- atlas-stream/src/main/resources/application.conf
- atlas-stream/src/main/scala/com/netflix/atlas/stream/DataSourceValidator.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalFlow.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
- atlas-stream/src/test/scala/com/netflix/atlas/stream/DataSourceValidatorSuite.scala
- atlas-stream/src/test/scala/com/netflix/atlas/stream/EvalFlowSuite.scala
Limit number of DataSources per session. 
Refactored DataSourceValidator to avoid passing extra parameters everywhere.
> atlas-stream: add limit for max-datasources-per-session

- atlas-stream/src/main/resources/application.conf
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
Reject requests if total number of datasources exceeds limit to avoid atlas-stream from overload and produce incorrect results.
> atlas-stream: reject requests if total datasources exceed limit

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
If there are a lot of new meters this can be a hot path.
> aggr: cache max number of meters value

- atlas-aggregator/src/main/resources/application.conf
Make it match settings from the publish cluster. See
Netflix/atlas#1127 for more details.
> aggr: allow shard tags

- atlas-persistence/src/main/resources/log4j2.xml
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
add hash prefix to s3 key for more even data distributeion; add padding for file sequence id for better sort alignment.
> atlas-persistence: hash prefix and format key name

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
Make services singleton so that their stopImpl will be called during shutdown
> atlas-persistence: make services singleton to make shutdown hook work

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
atlas-persistence: ensure S3CopyService is shutdown after LocalFilePersistService
> atlas-persistence: ensure S3CopyService is shutdown last

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/FileUtil.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
File rename was not atomic, it some times cause early termination of waiting during shutdown before all files are processed
> atlas-persistence: make file rename atomic to fix early termination

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
It seems like the s3 async client call never finishes occasionally (a few files after 2 days), with current flow, those file never get a chance to be re-processed in such cases. So setting a timeout from our end, release from dedup map when timeout and let file listing trigger the re-process.
> Timeout for s3 call and retry by listing file

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AggrConfigSuite.scala
Adjust the initial polling delay on the aggregator
to help spread out the requests to the downstream
clusters. It was initially aligned to the start to
maximize the amount of time to send the data. With
recent changes to run larger aggregator clusters
that have less data to send per node, this can
create a thundering herd for the connections.
> aggr: adjust initial polling delay

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- project/Dependencies.scala
The charset will get checked and fixed while parsing the
payload so this secondary check is not necessary.
> aggr: disable validation for registry

- build.sbt
rename root project to iep-apps to be more IDE friendly
> rename root project to iep-apps

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/AvroTest.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/RollingFileWriterSuite.scala
- build.sbt
- project/Dependencies.scala
Enable data compression to reduce output file size.
> atlas-persistence: enable data compression

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
This has the same effect overall, but results in fewer calls to the broker and slightly less overhead overall.
I'm unable to prove this make a material difference when testing locally.
The motivation is due to feedback that populating Lumen drop-downs is taking too long.
> Use union datasource when querying for tags

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/AvroTest.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/RollingFileWriterSuite.scala
- build.sbt
- project/plugins.sbt
Switch to avro's GenericRecord APIs to avoid overhead. 
Currently a specifc java class is generated for Datapoint and its instances are used for writing to avro file, but that creates quite some overhead because it creates every new instance by reflection(Class.forName), and eventually come down to the same path of generic type and writer.
It also simplify project setup since we don't need the extra step of code gen and schema compilation stuff.
> atlas-persistence: use generic avro type to avoid overhead

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileFlow.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/RollingFileWriterSuite.scala
Single thread seems to be one of the bottlenecks, allow parallelization to potentially increase throughput.
> atlas-persistence: parallelize file writing flow

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/FileUtil.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/PersistenceApi.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileFlow.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/RollingFileWriterSuite.scala
- project/BuildSettings.scala
Currently data points from request is being add to queue one by one, this creates high sync contention for underlying BlockingQueue when data points per second reaches over 100K/s. With this change, only one data point list per request is passing through the queue, so it reduces sync contention significantly.
Also fixes some Scala warnings.
> atlas-persistence: unflatten datapoint list

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/PersistenceApi.scala
During server or app shutdown, taking requests after queue closed causes data loss. Adding a check at Web API to reject requests after queue closed should fix this issue.
> atlas-persistence: reject requests after queue closed

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/FileUtil.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/S3CopySinkSuite.scala
Put files with the same start/end minute into a sub folder in s3. 
This makes file matching by range easier for downstream data processing pipeline. In theory it can create up to 1830(60+59+...+1) folders for an hour, but in reality I'd expect actual number to be much smaller because data points are mostly in order and range for a file is small, e.g. assume max range per file is 3 min, max num of folders <= 3*60.
> persistence: bucket files by start time to make range search easier

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
If no datasources match, then don't submit the query. Instead respond with none immediately.
This was my miss on an earlier PR - sorry 😬
> druid: Skip query if there are no datasources

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Adding a filter on the metric value itself has a huge effect on query performance when there are sparce metrics.
Sparse metrics: Where a row has only 1 metric value defined, the others are null (or 0)
Sparse metrics combined with dimensions used across metrics, such as percentile, mean that we aggregate a lot of zeros, as well as grouping-by dimension values that may not be present in the final resultset.
Omitting these rows early with a filter significantly helps query performance in these situations.
> druid: Add filter clause for non-zero metric value

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/FailureMessage.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- project/Dependencies.scala
For more information see Netflix/atlas#1203. It might be
possible to reduce some of the duplication with PublishApi,
but need to ensure it doesn't cause problems and that can
be done at a later time if needed. Currently aggregator
does some of the validation as parsing to reduce the overhead.
> include tags in validation responses

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
When we introduce new metric names, the value of that metric in older segments is null. When doing a group-by query, these segments without the metric will still perform aggregations. Filtering out nulls means the historical nodes can quickly remove rows that won't contribute
> druid: Filter null metrics

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
The addition of the regex query adds ~25% to the query time and is not needed to perform the query that we're trying to do (get all possible tag values)
> druid: Remove unneeded regex query when searching

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
Use regex filter with lowercase extraction function and lowercase the regex query. Extraction functions are applied to the value prior to applying the filter, but the matched value is returned unchanged.
> druid: Avoid using javascript filter

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Helps for debugging which expressions were impacted and in
some cases tracking back to a bad expression that is causing
failures.
> include exprs in cloudwatch request failure log

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
Remove the time check for the string cache. Some testing
shows that the `expireAfterAccess` significantly reduces
the throughput and adds little value for this use-case.
> aggr: only use max size for string cache

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
Default behavior changed in 2.13.4. Until we have time to
test properly, switch back to using old behavior.
> switch to opportunistic EC

- project/Dependencies.scala
There is a memory leak in 2.6.11 impacting some use-cases.
> akka 2.6.10

- iep-archaius/src/main/scala/com/netflix/iep/archaius/Main.scala
Simplify main and add an explicit config binding. Since
this is the dynamic properties source, it uses static
settings and that doesn't vary for internal deployments.
> archaius: add explicit config binding

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
Adds a metric to track the raw payload size for the set
of expressions to sync from lwcapi. Also converts the
number of expressions metric to a matching distribution
summary.
Minor cleanup: 1) inject actor system, and 2) avoid
creating a copy of the response as a byte array to parse
the data.
> lwc bridge: add metric for payload size

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
- project/Dependencies.scala
Updates the decoder to map it directly to a spectator
id and skip the intermediate SmallHashMap. This should
reduce the overhead for that conversion which on some
clusters is around 30% of the CPU time used.
> aggr: decode directly to id

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
By default use the region for the AWS client rather than
where the forwarder app is deployed. They will usually
be the same, but in some cases the region can be overridden.
> lwc-cloudwatch: use region for aws client

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
Adds support for a configurable rollup policy on the
aggregator. The format is the same as the rollup policies
that can be used with the AtlasRegistry.
> aggr: configurable rollup policy

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
Rename from `/stream` to `/sse`. The websocket usage for
`/stream` prevents the POST from being used. Since the
SSE output is useful for testing with curl, rename to make
it accessible.
> rename stream POST endpoint

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
Avoid conversion to generic processor as it isn't needed
here and adds overhead. Also change to using tick rather
than repeat and throttle.
> stream: use flow rather than processor

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/BridgeApiSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/StatsApiSuite.scala
If there are a lot of expressions in the index, then
removals can be quite slow. For that case of removing
many expressions it will now just recreate the index
instead. Also adds counters to track the number of
expressions added and removed.
> lwc-bridge: more efficient expression removal

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Add simple check on intermediate data size to avoid
GC issues on some responses that have a really high
cardinality.
> druid: add limit for data size

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
Update the expression sync to use the more efficient
remove method. Should avoid issues with removes being
much slower than add and leading to a really long time
to sync the set of expressions.
> bridge: use more efficient remove

- .gitignore
- atlas-cloudwatch/src/main/resources/nlb.conf
Add full listener breakouts for metrics that have them.
Remove listener tagging from metrics that do not have breakouts.
> update nlb metrics

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/resources/tgw.conf
These will allow teams to monitor for specific instances of exceeding
configured limits within a sample period, as opposed to monitoring the
average rate over a sample period.
> add tgw max metrics and tgw-attach dimension

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/resources/vpn.conf
This change also sorts the mappings by name in the reference configuration,
so that it is easier to tell if we have mappings defined for a given name.
> add vpn site-to-site metrics

- atlas-cloudwatch/src/main/resources/vpn.conf
The VpnId and and TunnelIpAddress dimensions are not both present on
the metrics that are published - it is one or the other. Each VPN
connection has two tunnels, a primary and a backup, and the preference
is to monitor these metrics based on VPN connection. As a result, we
will drop the TunnelIpAddress dimension.
> fix vpn metrics

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
This is a requirement for Druid TopN queries, they are rejected if >= Int.MAX_VALUE
> [patch] Use limit only if less than Int.MAX_VALUE

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
If an offset is present, then map it in as an additional
clause on the query. Otherwise clients following pagination
can end up in an endless loop because the same response
will keep getting returned with the same offset location.
> druid: honor offset for tag queries

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/ListMetricsActor.scala
Throttling errors are fairly common and lead to a lot
of noise. Change these to be a debug level.
> use debug level for throttling exceptions

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AtlasAggregatorService.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AggrConfigSuite.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AppModuleSuite.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
- project/Dependencies.scala
Use Akka-Http client for sending data instead of the
default which is based on the URLConnection class built
into the JDK. This helps reduce the number of threads
needed overall.
> aggr: use akka client for publishing

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Use a source entity and perform the smile encoding as
part of the source. This allows better concurrency since
the encoding will now be done via the dispatcher pool.
Tuning for the pool maybe needed, but will be looked at
after some more testing.
> encode payload as part of entity source

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Write directly to the json generator rather than using
the mapper. Since this is a hot path and the objects
are fairly simple this change helps reduce the overhead
for encoding the payloads.
Also refactors so the encoding is not part of the entity
source. This helps make it clear whether the latency is
due to the encoding or the actual network call.
> reduce overhead for encoding payloads

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Ensure stream failures will get logged to help with
debugging.
> log client stream restarts at warn level

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Update akka publisher to discard the entity bytes
for the response.
> ensure response entity is consumed

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Allows the set of datasources exposed to be filtered using
a regex. This can be useful for cases where there are some
datasources that should not be exposed for a given Druid
cluster.
> druid: add configurable filter for datasources

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
Include double in the set of data types that will get
treated as a counter value.
> druid: add double to counter types

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- build.sbt
- project/Dependencies.scala
Jdk16 strongly encapsulates the internals by default
causing problems for older versions of Guice. When
running on a newer JDK, have the build use Guice 5.
For the published library still need to use 4.1.0
to avoid creating problems internally for other
users stuck on old versions.
> update CI builds to include jdk16

- iep-atlas/build.sbt
- project/BuildSettings.scala
- project/GitVersion.scala
Replace in with [slash syntax].
[slash syntax]: https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
> fix build deprecation warnings

- project/Dependencies.scala
Pull in latest version for fix to [CVE-2021-44228].
[CVE-2021-44228]: https://nvd.nist.gov/vuln/detail/CVE-2021-44228
> log4j 2.15.0

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Adds a configuration setting that allows the metadata
interval to be different from the tag query interval.
This can be useful in some cases data is being migrated
from one datasource to another and thus would not have
recent data.
> druid: setting for metadata interval

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/BridgeApi.scala
- project/Dependencies.scala
Assume all datapoints in the incoming payload have the
same timestamp and perform a single increment on the
counter.
> use batch increment for received counter

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
Manifest doesn't work in scala3. Switch to using the
JavaTypeable helper from jackson-module-scala.
> switch from Manifest to JavaTypeable

- atlas-cloudwatch/src/main/resources/elasticache.conf
- atlas-cloudwatch/src/main/resources/memorydb.conf
- atlas-cloudwatch/src/main/resources/reference.conf
This implementation is similar the the elasticache redis metrics, with
metrics selection and naming following the existing conventions.
This covers the most useful host-level and cache metrics, and all of
the commandstats metrics.
> add memorydb metrics

- atlas-cloudwatch/src/main/resources/memorydb.conf
- atlas-cloudwatch/src/main/resources/reference.conf
This maps the ClusterName dimension to the aws.memorydb tag. The NodeId
dimension is already mapped to the nf.node tag.
Considering this mapping, the elasticache aws.node dimension is better
represented by nf.node, which is more in-line with existing common tags.
Add the EngineCPUUtilization metric, which is recommended for use when
there are four or more vCPU.
> add aws.memorydb tag

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/BridgeDatapoint.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/BridgeApiSuite.scala
If there is a conflict between the common tags and the
tags on a metric for a batch payload, then prefer the
tags local to the metric. This matches the precedence
behavior for the backends.
> lwc-bridge: prefer tags on metric to common tags

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
Fixes UnsupportedOperationException when using NOT clauses with either the `nf.datasource` or `name` dimensions.
> druid: fix UOE when using not clauses

- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/AppConfiguration.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/CwExprValidations.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExprInterpreter.scala
Spring doesn't do JIT bindings, so the Api instance created had null values for some of the injected
parameters. Add explicit bindings for those types.
> fix NPE for fwding admin

- atlas-slotting/README.md
- atlas-slotting/iamrole-example.md
- atlas-slotting/src/main/resources/log4j2.xml
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Grouping.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/GroupingSuite.scala
This flag reports whether or not the ASG is disabled, according to Netflix operational standards. The Launch process must be suspended on the ASG for this to be true.
Since we are adding one field to the ASG details, there will be a difference between data stored in DynamoDB and newly crawled data. This will trigger a merge on the first startup of the new code, which will preserve slot numbers for all existing instances. Future starts of the new code will update timestamps for unchanged ASGs.
> add isDisabled flag to asg details

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ConfigManager.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
When syncing the configs, there will be many updates in a short window. Before the config manager would forward the complete set of data sources for each message that is received. This has a large overhead downstream. Now it will only push the updated set of data sources when it receives a done or hearbeat message and there are pending changes.
> lwc-cloudwatch: reduce frequency of config updates

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AtlasAggregatorService.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingApi.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingCache.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingService.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/DynamoService.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesContext.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDao.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/MarkerService.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Purger.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesDao.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenService.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
These have been moved to jakarta in later versions. With the way we are using Spring, the annotations are not necessary.
> remove usage of javax annotations

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
Pass the id on the user query through to druid as part of the context. This can be useful understanding load on the druid clusters.
/cc @bsyk
> druid: add id to query context

- atlas-cloudwatch/src/main/resources/dx.conf
The affected metrics are all reported as aggregates (averages) over a five minute period by default.
> fix aws direct connect metrics

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AtlasAggregatorService.scala
Having multiple registry instances was a simple way to get more concurrency. However, it creates additional overhead for loading expressions from LWC. There are other ways to acheive the concurrency needed now.
> aggr: use a single registry instance

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Avoid creating a copy of the payload array when creating the ByteString object. Also uses a dedicated pool for encoding the payload.
> aggr: reduce allocations for encoding batches

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Before the offset was being ignored which could result in an endless loop for a user trying to paginate.
> druid: fix pagination for tag keys

- project/BuildSettings.scala
In preparation for Spring 6, drop support for jdk8 and jdk11.
> set baseline java version to 17

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/CaffeineCache.scala
- build.sbt
- project/BuildSettings.scala
- project/Dependencies.scala
Enable parallel polling of the meters and use a custom cache with a larger size than the default.
> aggr: tune evaluation settings

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Make the publisher queue size configurable. Adjust future to ensure it will always be completed even if the stream gets restarted. Now it will be completed when returned and treated as successful if it was enqueued. This avoids problems with the upstream hanging if the stream is restarted and some of the returned futures are never completed.
> aggr: ensure publisher future completes

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/FirehoseMetric.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/util/XXHasher.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/util/XXHasherSuite.scala
- build.sbt
- project/Dependencies.scala
parsed from the firehose Cloud Watch stream.
Also add an OpenHFT XXHash implementation utility for quickly calculating a unique hash on the Cloud Watch metric for caching.
> Atlas Cloudwatch: Add the FirehoseMetric case class for storing info

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishRouter.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishRouterSuite.scala
account ID map to route datapoints to the proper publish proxy endpoint.
> Atlas Cloud Watch: Add the PublishRouter that loads a stack to AWS

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
to determine if a value received from the Cloud Watch firehose has an exact match on the tags required in the configuration.
> Atlas Cloud Watch: add a dimension matching function to MetricCategory

- atlas-cloudwatch/src/main/protobuf/CloudWatchMetric.proto
- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
firehose metrics in a sorted list in a backing store like Redis. Add the protobuf complication SBT plugin to generate source code on package build.
> Atlas Cloud Watch: Add a protobuf definition file for storing the cached

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/resources/test-rules.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessorSuite.scala
for writing and reading from a backing store implementation. The processor is responsible for matching incoming fire hose data to rules and merging new values with existing values in the cache. It is also responsible for regularly scraping the cache and publishing the final data. Included is a simple local hash map based store for unit testing.
> Atlas Cloud Watch: Add the CloudWatchMetricsProcessor, an abstract class

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Update the encoding operation to use mapAsyncUnordered. The order is not important for this use-case and adds some overhead.
> order is not important for encoding

- atlas-cloudwatch/src/test/resources/test-rules.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessorSuite.scala
> Atlas Cloud Watch: Add a unit test validating separate min/max rules

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/AwsAccountSupplier.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/ConfigAccountSupplier.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConfigAccountSupplierSuite.scala
This will be used by the new poller for metrics that are unavailable via the firehose stream. For now there is a simple config based implementation but we'll have an internal implementation using internal tools.
> atlas cloudwatch: add an aws account supplier.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
This will be used for polling to determine when we need to poll for daily CloudWatch metrics.
> atlas cloudwatch: add last polled methods.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
This will be used to tell the app that a metric should be polled instead of expecting it from Firehose. E.g. S3 bucket aggregate metrics are computed and available daily. They are back-dated so that they won't arrive via Firehose.
> atlas cloudwatch: add polling offset to MetricCategory

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/spring/CloudWatchConfiguration.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/util/ExecutorFactory.scala
Used in the new poller to avoid tying up other threads. Shimmed for unit testing.
> atlas cloudwatch: Add executor factory.

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/GetMetricActor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/ListMetricsActor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/spring/CloudWatchConfiguration.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/resources/test-rules.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessorSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/NetflixTaggerSuite.scala
- project/Dependencies.scala
This poller now focuses only on polling a small set of metrics once a day with heavy limiting but for multiple accounts and regions. This will be used for S3 bucket aggregate metrics and any other series that are unable to be processed through the Firehose stream due to back-dated timestamps.
> atlas cloudwatch: Rewrite CloudWatchPoller.

- atlas-cloudwatch/src/main/resources/alb.conf
- atlas-cloudwatch/src/main/resources/api-gateway.conf
- atlas-cloudwatch/src/main/resources/billing.conf
- atlas-cloudwatch/src/main/resources/dynamodb.conf
- atlas-cloudwatch/src/main/resources/ec2.conf
- atlas-cloudwatch/src/main/resources/elasticache.conf
- atlas-cloudwatch/src/main/resources/elb.conf
- atlas-cloudwatch/src/main/resources/es.conf
- atlas-cloudwatch/src/main/resources/events.conf
- atlas-cloudwatch/src/main/resources/iot.conf
- atlas-cloudwatch/src/main/resources/lambda.conf
- atlas-cloudwatch/src/main/resources/mediaconnect.conf
- atlas-cloudwatch/src/main/resources/medialive.conf
- atlas-cloudwatch/src/main/resources/neptune.conf
- atlas-cloudwatch/src/main/resources/nlb.conf
- atlas-cloudwatch/src/main/resources/rds.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/resources/route53.conf
- atlas-cloudwatch/src/main/resources/s3-request.conf
- atlas-cloudwatch/src/main/resources/s3.conf
- atlas-cloudwatch/src/main/resources/sns.conf
- atlas-cloudwatch/src/main/resources/sqs.conf
- atlas-cloudwatch/src/main/resources/vpn.conf
Another round of updates to tune the offsets for streaming. Also configure S3 and Neptune billing for polling. Fix some issues with typos in tags, wrong tag combinations  or incorrect posting intervals.
> atlas cloudwatch: Update AWS configurations.

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala
And remove the common nf.region tag from the reference.conf. Move it to the test application file instead. Entailed cleaning up a couple of DefaultTagger unit tests.
> atlas cloudwatch: add Per-VPC mapping.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/ConfigAccountSupplier.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
Since we can (and do) have multiple offsets running, we need a unique key in Redis for each. Updated with an ID.
Also log the config account supplier map.
> atlas cloudwatch: Fix polling timestamp API.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishRouter.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishRouterSuite.scala
This allows us to route by region as well as account. Necessary for the IEP stacks and maybe others in the future.
> atlas cloudwatch: Rework publish routing config.

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/AwsAccountSupplier.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/AwsConfigAccountSupplier.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/ConfigAccountSupplier.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/AwsConfigAccountSupplierSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConfigAccountSupplierSuite.scala
- build.sbt
- project/Dependencies.scala
The supplier polls an AWS Config database for the list of accounts and resources active in each region to avoid manual configuration and mappings. This change re-works the AwsAccountSupplier to return a map of accounts to regions to namespaces so we can only poll for the data that should be there, saving a bit of money. Also drops the future from that interface.
> atlas cloudwatch: add AWS Config account supplier.

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
This lets us recover a big more graceffully if a particular account or region has an issue when polling. Instead of tracking a flag and a key in redis for the whole job (all accounts and regions) track per account and region combo so that we can retry only those that fail. Also set the check for polling state to every 5 minutes instead.
> atlas cloudwatch: Poll flag per account and region.

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/resources/segmentMetadataResponse.json
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
These represent approximate distinct counts. We can treat them as longsum/counters. Usage will be nuanced, we'll probably need to ensure callers are performing per-step queries for the results to make sense.
> Add support for querying HLLSketch types

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
For most things in druid we assume they are counters. For sketches, that is not the case and it should just use the estimate.
> druid: do not convert sketches to a rate

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/test/resources/segmentMetadataResponse.json
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
There are 2 issues with Druid segment metadata
1. If a column type is changed, the entry for the column default to a string type and an errorMessage is populated. These column entries cannot be used. Since we treat all string columns as dimension, a metric that changes type gets listed as a dimension instead of a metric and as such cannot be queried.
2. The HLLSketchBuilder ingestion aggregator initially reports column type of `HLLSketchBuilder` but as soon as that is persisted into an actual segment it becomes `HLLSketch`. This results in the same symptom as (1) since the type appears to have changed.
We encounter problem (1) when someone accidentally adds a new metric as the wrong type and needs to fix it. e.g. as a `spectatorHistogramTimer` when it was supposed to be a …
> Segment metadata

- atlas-cloudwatch/src/main/resources/mediaconnect.conf
- atlas-cloudwatch/src/main/resources/medialive.conf
- atlas-cloudwatch/src/main/resources/reference.conf
Add metrics for mediaconnect and medialive.
> atlas cloudwatch: update media metrics.

- atlas-cloudwatch/src/main/resources/medialive.conf
- atlas-cloudwatch/src/main/resources/reference.conf
And fix ChannelId so it converts to aws.channel
> atlas cloudwatch: rename fillMsec

- atlas-cloudwatch/src/main/resources/ec2.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
Allows for polling more frequently, e.g. every 5m for the EC2 VPC metrics.
> atlas cloudwatch: remove polling filter.

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
Update the filter mapping to use a bound instead of using javascript for lt, le, gt, ge.
> druid: use bound instead of js

- atlas-cloudwatch/src/main/resources/medialive.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/DefaultTagger.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala
Add support for extracting multiple groups from extractors and combine them with a hyphen to shorten the MediaConnect source and flow ARNs. Update the regexes for those configs.
Also remove duplicate SourceARN and FlowARN mappings that were conflicting with the extractors, causing some metrics to report the fulle string and others to use the regex.
Bump MediaLive metrics to 4 minute offset.
> atlas cloudwatch: Fixes for Media* metrics

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/DefaultTaggerSuite.scala
Needed to match the pre-character-substitution string.
> atlas cloudwatch: Fix mediaconnect ARN pattern.

- atlas-cloudwatch/src/main/resources/reference.conf
Fix typo in the pattern for FlowARN and apply the pattern to the OutputARN
> atlas cloudwatch: MediaConnect ARN tuning.

- atlas-cloudwatch/src/main/resources/fsx.conf
Changing it to `aws.fsx.volume.operation.totalTime` to better reflect the fact that it is a total time to complete the operation, not a latency value that should be small.
> atlas cloudwatch: Update FSx operation latency.

- atlas-cloudwatch/src/main/resources/fsx.conf
This will convert the timer metric to the same name as the count and allow the two to be combined for `:dist-avg`
> atlas cloudwatch: FSx operations to timer.

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PekkoPublisher.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishQueue.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishRouter.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/spring/CloudWatchConfiguration.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishQueueSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishRouterSuite.scala
- atlas-druid/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
Rename to use Pekko for better consistency and making it easier to automate the transition of other projects that pull in these classes. Allows for easier search and replace to migrate.
> rename classes with Akka in the name

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
- project/Dependencies.scala
Rework the cloudwatch polling UT to avoid mocking out the stream response as it was failing with the SDK upgrade.
Fixes #486
> atlas-cloudwatch: Upgrade AWS SDK to 2.20.136.

- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Grouping.scala
- atlas-slotting/src/test/resources/SlottedInstanceDetails-0.json
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/GroupingSuite.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/SlottingApiSuite.scala
Add IPv6 address to the instance details. Also make the private IP address optional as it is null on instances running in an IPv6 only subnet.
> slotting: add IPv6 address to response

- atlas-cloudwatch/src/main/resources/api-gateway.conf
Looks like the namespace for these metrics changed at some point. It was fixed in 0.4.x branch, but not this branch which is still needed for some legacy polling.
> 0.3.x: fix namespace for ApiGateway

- atlas-cloudwatch/src/main/resources/api-gateway.conf
- atlas-cloudwatch/src/main/resources/reference.conf
For some specific accounts that need the detail.
Also add cache and backend latency metrics.
> atlas cloudwatch: add detailed tags to APIGateway config.

- atlas-slotting/README.md
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingApi.scala
- atlas-slotting/src/test/resources/atlas_app-main-none-v001.json
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/SlottingApiSuite.scala
The `/api/v1/clusters/:clusterName` path provides both an index view and a
verbose view of the stored slotting data. This view performs a Frigga cluster
name match on the AutoScalingGroup name and returns the result. This allows
a user to distinguish between `app-foo` and `app-foobar` when filtering.
The `/api/v2` paths which provided Edda compatibility have been removed. They
never implemented true compatibility, not having selectors, and thus were
misleading and made the API routes more complicated than necessary. There is
no usage of these endpoints outside of a few manual testing calls.
> add clusters path to filter slotting data

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/AppConfiguration.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
- build.sbt
Use client factory to create the S3 client. This allows it to be configured in a consistent way including enabling dualstack where appropriate.
> persistence: use AWS client factory

- iep-lwc-cloudwatch/src/main/resources/application.conf
Update AWS client configs for cloudwatch forwarding to include some clients for additional regions that are in use at Netflix.
> add regions for cloudwatch forwarding

- atlas-cloudwatch/src/main/resources/ec2.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/AwsConfigAccountSupplier.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
Polls at 60s. Disabled the other EC2 system metrics to avoid polling. Also log the polling offset at completion and log the accounts resolved from the account config.
> atlas cloudwatch: enable polling for EC2 status check failures.

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
Uses a placeholder name of unknown if the query for an aggregate function has no exact tags. This matches the behavior of the backend. See also Netflix/spectator#1097.
> lwc bridge: aggr function with empty tags

- atlas-cloudwatch/src/main/resources/ec2.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
Pick up the EC2 StatusCheckFailed metric as the others were not incrementing under test.
Add an allow list for the 60s polling as a hack to avoid cost overruns. TODO - clean up the code for proper per-account overrides on multiple levels.
> atlas cloudwatch: Throttle AWS polling requests.

- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/DynamoOps.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Grouping.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingService.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Util.scala
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/DynamoOpsSuite.scala
Just keep the data as String/Array[Byte] and avoid unecessary conversions to and from ByteBuffer. All operations were first converting to intermediate byte array or other type anyway.
Also update log messages to properly log the exception so the stack trace will be present in the logs.
> slotting: avoid ByteBuffer conversions

- atlas-cloudwatch/src/main/resources/neptune.conf
Also sync with latest metrics from AWS docs.
> atlas-cloudwatch: Neptune to db instance level metrics.

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Allow data to be forwarded at higher resolution if enabled on the stream.
> lwc-cloudwatch: support high resolution

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
The name key was special cased for the existence check, but wasn't checking other conditions like the length.
> aggr: fix validation checks for name

- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDao.scala
TableName is a required field for GetItem command on DDD 
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html#DDB-GetItem-request-TableName
AWS SDK Exception
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: 1 validation error detected: Value null at 'tableName' failed to satisfy constraint: Member must not be null (Service: DynamoDb, Status Code: 400, Request ID: VRR1NLEMF2J180HKII229KAK57VV4KQNSO5AEMVJF66Q9ASUAAJG)
```
> Update GetItemRequest Builder with TableName Param

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Before it was hard-coded to 60 when creating the data source so the step on the URI would not get honored.
> lwc-cloudwatch: use step size from uri

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
This helps avoid some confusion if the last character is a carriage return. When viewing logs on the console that can make it hard to view properly.
> lwc-cloudwatch: trim messages before parsing

- iep-lwc-cloudwatch/src/main/resources/application.conf
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Allows put calls to be disabled. This can be useful to run in parallel for testing without actually sending data to CloudWatch.
> lwc-cloudwatch: add flag to disable put

- iep-lwc-cloudwatch/src/main/resources/application.conf
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/AppConfiguration.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ConfigStats.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/StatsApi.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Keep track of number of expressions that are not receiving any data. Also adds stats API to get a detailed breakdown.
> lwc-cloudwatch: add gauge for stale expressions

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessorSuite.scala
The number of metrics is fairly low and we need a bit more info around latencies.
> atlas cloudwatch: Add metric dimension publishing metrics.

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Adjust the timestamp for data forwarded to CloudWatch. It was off by one step interval due to differences in how Atlas and CloudWatch indicate the timestamp. Atlas uses the end of the step interval, CloudWatch uses the start.
> lwc-cloudwatch: fix timestamp

- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Api.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/CwExprValidations.scala
Derive step from the URI rather than using a hardcoded value of zero.
> cw admin: fix step for streaming check

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
This avoids some allocations to add it in later when the counter or max gauge is created.
> aggr: set dstype when loading tags

- atlas-cloudwatch/src/main/protobuf/CloudWatchMetric.proto
- atlas-cloudwatch/src/main/resources/cloudhsm.conf
- atlas-cloudwatch/src/main/resources/dynamodb.conf
- atlas-cloudwatch/src/main/resources/opensearch.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchDebugger.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricData.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/webapi/CloudWatchFirehoseEndpoint.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/webapi/RulesEndpoint.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/BaseCloudWatchMetricsProcessorSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CWMPInsertSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CWMPProcessSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CWMPPublishPointSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessorSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionsSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDataSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishRouterSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessorSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/webapi/CloudWatchFirehoseEndpointSuite.scala
The manually configured offsets were error prone and added delay. Now we tag values as published and find the oldest valid non-published value and push that. We still need periods configured for each metric but this mechanism allows for out of order data and changes in publishing delays (now that AWS supports 0 time buffering on data firehoses.) The publish flag means additional writes during scrapes but it should still scale until we need to split scrapes for leaders across instances.
Timestamps in the cache are no longer normalized and we now record the time the value written to the cache. This will let us handle higher-resolution data eventually and help debug period missconfigurations. Data could also be lost when updates for the same series came in different threads from the …
> cloudwatch: Rework to improve data accuracy.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CWMPProcessSuite.scala
Add aws.metric tag to filter metric counter, to confirm which all metrics names are getting filtered out
> Add aws.metric tag to filter metric counter

- atlas-cloudwatch/src/main/resources/ec2.conf
- atlas-cloudwatch/src/main/resources/s3.conf
Re-enable metrics for EC2 and disable polling.
> cloudwatch: Disable polling on S3 now that AWS is streaming the data.

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
In some cases if misconfigured the metric name can be mapped to `null` which was leading to an NPE. Filter them out to allow other data to be picked up.
> druid: ignore null metadata mappings

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
Druid 29 deprecated the `lenientAggregatorMerge` option and replaced it with `aggregatorMergeStrategy`
Docs: https://druid.apache.org/docs/latest/querying/segmentmetadataquery/#aggregatormergestrategy
> [Druid] Adjust metadata query to be compatible with Druid v29.x

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppConfiguration.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AtlasAggregatorService.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PekkoClient.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PekkoPublisher.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/ShardedAggregatorService.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/CwExprValidations.scala
- project/Dependencies.scala
Adds optional mode that can be used to shard the data across multiple aggregator clusters. This can be helpful to scale out while keeping the updates for the same meters on a small subset of nodes. Helps reduce duplication across the instances in the cluster.
> aggr: add support for sharding

- atlas-cloudwatch/src/main/resources/api-gateway.conf
- atlas-cloudwatch/src/main/resources/reference.conf
Also fix mappings for ApiName to aws.resource and Stage to aws.stage. The old pollers were mapping the ApiName to resource.
> cloudwatch: add Stage to the API Gateway.

- atlas-cloudwatch/src/main/resources/api-gateway.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchRules.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/webapi/RulesEndpoint.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/resources/test-rules.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CWMPProcessSuite.scala
Some accounts opt in to detailed metrics, meanin additional tags. This change lets us supply configurations for multiple dimension sets.
Fixes the API gateway metrics to have both detailed and non-detailed.
> cloudwatch: Enable detailed and non-detailed metrics.

- atlas-cloudwatch/README.md
- atlas-cloudwatch/src/main/resources/lambda.conf
Update the readme about standard vs detailed tag sets.
> atlas cloudwatch: add standard tags for Lambda.

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/ReduceStepTimeSeq.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
Update so that some data sources can be more granular than others and get blended together on the graphs. If a data source doesn't support the fine granularity, then it will be retrieved at its supported granularity and mapped to the requested step for the graph.
This will not work for data sources that are consolidated historically. That would add quite a bit of complexity to processing the data, but may be desirable in the future to help mitigate cost.
> druid: support data with mixed step sizes

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
The routing exception handler was missing an AWS namespace value when recording metrics on routing exceptions resulting in an error that threw off processing a batch. Now we properly record and log the exception without throwing.
> cloudwatch: Fix metric recording exception.

- atlas-cloudwatch/src/main/resources/dx.conf
Add DX ConnectionCRCErrorCount and ConnectionEncryptionState
> atlas cloudwatch: Fix typo for DX `ConnectionErrorCount`

- atlas-cloudwatch/src/main/resources/mediaconnect.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
Add a High resolution metric polling frequency of 5 sec and adding few more metric which are getting non-zero values
> cloudwatch_poller: Keep a 5sec frequency for high resolution metrics poller

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchDebugger.scala
- build.sbt
Phase out usage of legacy QueryIndex.
> cloudwatch: switch to spectator QueryIndex

- atlas-druid/src/main/scala/com/netflix/atlas/druid/AppConfiguration.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidMetadataService.scala
Add a service included in the healthcheck to ensure that the metadata has been updated at least once before marking the service as healthy. Before it could become healthy even if it was failing to refresh the metadata.
> druid: ensure metadata is available when starting

- build.sbt
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/AppConfiguration.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/BridgeApiSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/StatsApiSuite.scala
To ease debugging make the set of subscription ids to log a dynamic property.
> lwc-bridge: allow ids to log to be set dynamically

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishQueue.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishRouter.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/package.scala
* ``sendToRegistry `` does not require full category scan to match a given metric-name, we can pass the existing metadata from poller, to directly transform to an Atlas datapoint.
* Added some more metric/tag/logs for debugging purpose only, will remove later as this will be 5s frequency noise.
> Simplify polled cw-dp to atlas-dp match/conversion

- atlas-slotting/README.md
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/DynamoOps.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Grouping.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingApi.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingCache.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingService.scala
- atlas-slotting/src/test/resources/atlas_app-main-all-v002.json
- atlas-slotting/src/test/scala/com/netflix/atlas/slotting/SlottingApiSuite.scala
Provide a few additional views of the data, to assist with exploration and an alternate means of parsing.
Fix warnings for methods that can be marked private.
> add api endpoints for clusters

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
Without a name clause, it can result in many broad druid queries that are quite expensive. These vague queries can be common as intermediates when building a query, but are not typically useful.
> druid: require name clause on queries

- atlas-cloudwatch/src/main/resources/msk-serverless.conf
- atlas-cloudwatch/src/main/resources/reference.conf
InfraAPI is using AWS MSK Serverless for event streaming. Adds MSK serverless metrics config for atlas. See https://docs.aws.amazon.com/msk/latest/developerguide/serverless-monitoring.html for metrics details.
> Create MSK Serverless scrape config

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishRouter.scala
If we have defined a routing for region ``r1`` => ``r2``
---------------
* < r1 :: Queue(r2)>         ``any r1 data will go to r2``      
* < _DEFAULT :: Queue(r2)>   ``all other regions data will go to r2``    
---------------
* < r1 :: Queue(r2)>                  ``any r1 data will go to r2``       (No Change)
* < _DEFAULT :: Queue(r1)>     ``any non r1 data should go to r1 (not an ideal case)``
* < _DEFAULT :: Queue(r2)>     ``any non r1 data should go same as defined routing``
> fix DEFAULT queue, if current region routing is defined

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
For some aggregations, we were repeating the same timestamp, resulting in higher than expected values combined in the registry. Now we'll only emit new values.
> atlas cloudwatch: Cache the last timestamp of a high res poll.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchDebugger.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
Fix backfills to look at the normalized times
Fix some logging to avoid overcounting stale and backfills
> atlas cloudwatch: Normalize high res scrape timestamps

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Log warning for specific metadata request that fails. Makes it easier to debug since the primary information is in the payload. Also disable warnings about invalid ETag headers coming back from druid.
> druid: add warning log for segment metadata

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExpressionsEvaluatorSuite.scala
If both sides of an OR clause matched an id, then it was adding the datapoint multiple times since the index uses a DNF with each OR clause considered separately. We now dedup the matches to avoid updating the data point multiple times.
> lwc-bridge: avoid double counting with OR

- atlas-cloudwatch/src/main/resources/mediaconnect.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/Conversions.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishQueue.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishRouter.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/poller/PublishClient.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CWMPProcessSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/ConversionSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricCategorySuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/MetricDefinitionSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishQueueSuite.scala
Fixes an issue where the high-res  rate was not reporting to the stream or backend properly. And fix the MediaConnect source bit rate name to reflect it is converted to bytes. Also cleanup the pub router config duplication a bit.
> atlas cw: Move high res cumulative rate conversion to the publish queue.

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
Update integration to handle the percentile dimension that is part of the histogram type on druid. As a result if trying to restrict based on that dimension, the histogram must be maintained and the restrictions evaluated locally.
This allows operations like `:sampie-count` to work when using the druid bridge.
> druid: support restrictions on percentile dimension

- .github/workflows/pr.yml
- build.sbt
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/MarkerService.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ApiSuite.scala
- project/BuildSettings.scala
- project/Dependencies.scala
Enables cross-building for scala 3 on most sub-projects. The cloudwatch sub-project is skipped because the mockito stuff is not compatible with scala 3.
> enable cross-building for scala 3

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
- project/Dependencies.scala
For druid the data sources can potentially have different step sizes. With this change, it will choose the maximum step size across all potential data sources that could match an expression on the graph and the computed context step.
If a higher resolution metric is included on the same graph as a lower resolution metric, the lower resolution will be used for both so the data will align for math and stats.
> druid: adjust the step based on the datasource

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
For some test clusters there are a lot of bad data sources that pop up and have failures loading the segment metadata. Add an option to ignore those so it doesn't impact other usage.
> druid: support ignoring metadata failures
