- iep-archaius/src/main/scala/com/netflix/iep/archaius/Main.scala
> use builder to create dynamo db client

- build.sbt
- iep-lwc-bridge/README.md
- iep-lwc-bridge/src/main/resources/application.conf
- iep-lwc-bridge/src/main/resources/log4j2.xml
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/Main.scala
- project/Dependencies.scala
This is an initial version of a simple bridge app
to map data flowing into the publish API and forward
it to LWC. Addresses Netflix/atlas#577.
> initial bridge from publish to lwc

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
This will always use a 200 response type. The
assumed use-case is a proxy that tees the
requests to both a typical publish endpoint and
this cluster. The user response should come
from the publish endpoint with the response
here merely acknowledging receipt. For now to
avoid spurious retries and confusion this
response is always OK.
> always return OK to the user

- .travis.yml
- project/Dependencies.scala
- project/plugins.sbt
We are now moving all internal builds to use 2.12
by default.
> update to scala 2.12

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Moves the recover logic for the entity source to
the correct place. Also changes the retry source
to flatMap the source for a single connect including
the data bytes so the retry will be backpressured
until the request fails overall. Before it could
continue to make requests as soon as a response
was received.
> fix auto-reconnect for configbin source

- .travis.yml
- scripts/buildViaTravis.sh
Enable build and tests on both jdk8 and jdk9.
> enable build for jdk9

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/resources/log4j2.xml
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidSort.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/Main.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/package.scala
- atlas-druid/src/test/resources/application.conf
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
- build.sbt
Experiment for using Druid as a backend datastore with
the Atlas query APIs. This is a quick prototype and should
not be used in any critical scenarios.
> initial prototype for fronting druid

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Fixes the forwarder to use the CloudWatch namespace
that is specified in the config instead of a hard
coded value.
> use the namespace from the config

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/Main.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/Main.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesContext.scala
- iep-archaius/src/test/scala/com/netflix/iep/archaius/PropertiesApiSuite.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/AppModule.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Mostly minor unused variables and methods along with
change spectator call to use the PolledMeter helper.
> fix deprecation and compiler warnings

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
The vast majority of the evaluated expressions we have
internally have an exact match on the app and the name.
With this change the bridge will group the expression
set by both in the evaluator to reduce the number of
expressions that have to be checked for any given datapoint.
On an internal test node with real traffic this improved
RPS by about 10x.
> update the expr groups to include app and name

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateActor.scala
This should be the group name not the multiple
possible matches selector.
> fix key used for fallback expr summary

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
For now all druid data is assumed to be counters and the
values we get back are a rate per step. This changes them
to a rate per second to be consistent with Atlas sources.
We may need to revisit in the future, but we'll need to
figure out how to automatically understand the typing on
the druid side first.
> convert druid values to rate per second

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
This is to catch cases where Druid seems to be ignoring
the filter if it matches one of the dimensions for the
grouping.
> apply local filter for druid query results

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
The dimension spec does not work for search queries and
there are some filters that cannot be represented there.
Adds a local filter step to the search query processing
similar to what we are already doing for group by.
> fix tag query filtering of multi-value dimensions

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
- build.sbt
Makes it easier to debug the current contents of the
aggregate registry.
> add admin endpoint for aggr registry

- build.sbt
- project/Dependencies.scala
Pull in fix for Netflix/spectator#589.
> update to spectator 0.73.0

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/AppModule.scala
```
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Binding points to itself.
at com.netflix.iep.lwc.AppModule.configure(AppModule.scala:24)
```
> fix guice initialization error

- .scalafmt.conf
- Makefile
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppModule.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AppModuleSuite.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidFilterSuite.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
- build.sbt
- iep-archaius/src/main/scala/com/netflix/iep/archaius/DynamoService.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/Main.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesApi.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesContext.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesLoader.scala
- iep-archaius/src/test/scala/com/netflix/iep/archaius/PropertiesApiSuite.scala
- iep-archaius/src/test/scala/com/netflix/iep/archaius/PropertiesLoaderSuite.scala
- iep-clienttest/src/main/scala/com/netflix/iep/clienttest/InstrumentationService.scala
- iep-clienttest/src/main/scala/com/netflix/iep/clienttest/MetricLibrary.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/UpdateApi.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/StatsApiSuite.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ConfigManager.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Uses the same config as Atlas (Netflix/atlas#666).
> scalafmt config to help ensure consistency

- build.sbt
- iep-ses-monitor/README.md
- iep-ses-monitor/src/main/resources/application.conf
- iep-ses-monitor/src/main/resources/log4j2.xml
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/AppModule.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/Main.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
- project/Dependencies.scala
This service consumes SES sending activity notifications and publishes
key aspects as metrics. It additionally logs the full notification to
disk.
> Initial version of SES monitoring service

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
Moves the expression sync from with the stream stage to
running in the background with a future. This step can
potentially take a long time if there are a lot of
expressions which can then lead to problems refreshing
the data.
> execute expression sync in future

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
Takes a list of URIs and performs static checks to ensure
they can be executed using the evaluator.
> add basic validation endpoint

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExpressionsEvaluator.scala
Fixes compile error after changes in Netflix/atlas#989.
> update query index usage to use array

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Keys used as part of a query clause that can return a set of
values need to be included as part of the result set so we can
perform the local evaluation step. Before this change the user
would incorrectly get an empty result if `:re` or similar ops
were used with a key that was not included in the explicit set
of group by keys.
> druid: add range query keys to group by dimensions

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
If there is no data, then the `nf.account` will not be
available and it can cause spurious errors due to trying
to assume role into a bogus account.
> filter out NaN values

- build.sbt
- iep-lwc-cloudwatch-model/src/main/scala/com/netflix/iep/lwc/fwd/cw/ExpressionId.scala
- iep-lwc-cloudwatch-model/src/main/scala/com/netflix/iep/lwc/fwd/cw/Report.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
- iep-lwc-fwding-admin/schema/ExpressionDetails.json
- iep-lwc-fwding-admin/schema/README.md
- iep-lwc-fwding-admin/src/main/resources/application.conf
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Api.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/AppModule.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDao.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Main.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/MarkerService.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ApiSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ExpressionDetailsDaoSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/MarkerServiceSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ValidationSuite.scala
Process the incoming reports and store the
no data state of a cw forward expression in
DynamoDB
> Marker service initial implementation

- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
The `UnknownHostException` is wrapped in an `SdkClientException` when
a failure of that sort occurs during SQS queue URI retrieval, so needs
to be unwrapped.
> Unwrap SdkClientException to determine retry

- Makefile
See Netflix/atlas#1016 for more details.
> explicitly fetch tags for build

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/UpdateApi.scala
Updates to handle recent changes made in Netflix/atlas#1027.
> fix compile errors for lwc bridge

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
Mostly related to type annotation for implicits and unused
variable names for pattern matches.
> fix some minor warnings

- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingApi.scala
When using encodeResponse, then Subsequent access to the
cached entity fails because the gzip encoder has already
been closed. Now the compression will be handled when
creating the response object so it will have a strict
entity.
> avoid using encodeResponse inside cache directive

- iep-ses-monitor/src/main/resources/application.conf
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/AppModule.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
- project/Dependencies.scala
alpakka-sqs 1.0.+ uses AWS SDK v2, so this update required adapting to those
changes as well.
Issue #151
> Update akka-stream-alpakka-sqs to 1.0.2

- .travis.yml
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AppModuleSuite.scala
- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/Grouping.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
- project/Dependencies.scala
- project/sbt
Only minor code changes were needed.
> cross-build for scala 2.13

- Makefile
The makefile wasn't passing the scala version from travis
to SBT.
> fix 2.13 travis builds

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
Before any range query would get included in the dimension
list so that local filtering would work correctly. It is now
limited to keys that are explicitly in the group by. The
local filtering should still avoid problems with multi-value
keys that are included in the group by. The eval step will
only check the exact key matches to avoid over filtering
based on context that is no longer part of the result.
> druid: limit dimensions in grouping

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
This may be more efficient on the druid server.
> druid: use timeseries query if dimension list is empty

- iep-lwc-loadgen/src/main/resources/log4j2.xml
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/AppModule.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
add service connecting to atlas-stream websocket endpoint
> iep-lwc-loadgen: add service connecting to atlas-stream websocket endpoint

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
use only 1 WebSocket flow, better control of number of uris.
> iep-lwc-loadgen: use only 1 WebSocket flow 

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
iep-lwc-loadgen: simplify metrics and add log
> iep-lwc-loadgen: simplify metrics and add log

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
iep-lwc-loadgen: add a way to log result message
> iep-lwc-loadgen: add a way to log result message

- atlas-stream/src/main/resources/application.conf
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
- atlas-stream/src/test/scala/com/netflix/atlas/stream/EvalFlowSuite.scala
atlas-stream: configurable queue size; grep friendly log message
> atlas-stream: configurable queue size; grep friendly log message

- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
loadgen: make it auto reconnect with flow restart
> loadgen: make it auto reconnect

- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
- project/Dependencies.scala
> atlas-stream: use Evaluator flow API

- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalFlow.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
atlas-stream: sending some info messages for websocket api
> atlas-stream: sending some info messages for websocket api

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Before we would push the limit for the number of results
to the search query as an optimization to reduce the amount
of data coming back from Druid to only what was needed.
The problem is that for multi-value dimensions if any value
for a given record matches, then all values for that record
will get returned. Those will get filtered locally, but with
a limit on the Druid side, the value we are looking for may
be past that limit and cause an empty result set.
> druid: do not limit search query response size

- atlas-persistence/README.md
- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/resources/log4j2.xml
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/AppModule.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/Main.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/PersistenceActor.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/PersistenceApi.scala
- build.sbt
Atlas-persistence skeleton, simply log data points.
> atlas persistence api skeleton

- build.sbt
include atlas-persistence in root aggregate
> include atlas-persistence in root aggregate

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Allows druid historical clusters to filter out some empty
values and reduce the result size coming back to the broker.
> druid: explicitly check for group by dimensions

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/resources/log4j2.xml
- atlas-persistence/src/main/resources/reference.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/FileUtil.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/FileWatchSource.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileSink.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
- build.sbt
- project/Dependencies.scala
upload locally batched files to S3
> upload locally batched files to S3

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileSink.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/AvroRollingFileWriterSuite.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/AvroTest.scala
atlas-persistence: basic error handling with auto restart, logging and metrics
> atlas-persistence: basic error handling

- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/AvroTest.scala
atlas-persistence: revert accidentally deleted line for test util
> atlas-persistence: revert accidentally deleted line for test util

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/PersistenceApi.scala
atlas-persistence: support batch payload
> atlas-persistence: support batch payload

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileFlow.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
covert RollingFileSink to flow and wait for its complete on shutdown
> atlas-persistence: wait for write flow complete in shutdown

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/FileUtil.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- project/Dependencies.scala
Ensure the directory stream is closed after processing
the results.
> fix fd leak for listing files

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
In practice it tends to have a really low hit rate.
> aggr: remove id cache

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
atlas-persistence: change data format to be consistent with existing ones;
also fixed a typo
> atlas-persistence: change data format to be consistent

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
atlas-persistence: add log and metric to track file closing error; fix some scala best practice warnings
> atlas-persistence: add log and metric to track file closing error

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
- build.sbt
- project/Dependencies.scala
Avoid fd leak issue of async S3 client
> atlas-persistence: switch to sync s3 api copy

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/RollingFileWriterSuite.scala
atlas-persistence: allow specifying compression level for deflate
> atlas-persistence: allow specifying compression level for deflate

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/AppModule.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
atlas-persistence: improve config/health checks
> atlas-persistence: improve config/health checks

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
This is a custom wrapper that is more efficient for some
use-cases because it can avoid a lot of allocations for
tuple/option objects that occur when sticking to the Scala
Map interface.
> persistence: use SmallHashMap.asJavaMap

- atlas-persistence/src/main/resources/application.conf
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
persistence: set work size dynamically based on number of cores
> persistence: set work size dynamically based on number of cores

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
persistence: use SourceQueue.isOpen for health check
> persistence: use SourceQueue.isOpen for health check

- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/AvroTest.scala
- atlas-stream/src/test/scala/com/netflix/atlas/stream/DataSourceValidatorSuite.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPolicies.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/TimerSuite.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
Fixes various compiler warnings that were introduced
after bumping to 2.13.3.
> fix compiler warnings

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/ForeachApi.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidClientSuite.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileFlow.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopyService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalFlow.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/EvalService.scala
- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
- atlas-stream/src/test/scala/com/netflix/atlas/stream/EvalFlowSuite.scala
- iep-archaius/src/main/scala/com/netflix/iep/archaius/PropertiesLoader.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/LwcPublishActor.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/MarkerService.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Purger.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPolicies.scala
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesDao.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/MarkerServiceSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/PurgerSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ScalingPoliciesDaoSuite.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenService.scala
- iep-lwc-loadgen/src/main/scala/com/netflix/iep/loadgen/LoadGenWsService.scala
- iep-ses-monitor/src/main/scala/com/netflix/iep/ses/SesMonitoringService.scala
- iep-ses-monitor/src/test/scala/com/netflix/iep/ses/SesMonitoringServiceSuite.scala
Fixes deprecation warnings introduced with the latest
version of Akka and Akka-HTTP.
> fix warnings introduced with Akka 2.6

- .github/workflows/pr.yml
Test out using GitHub actions. For now it is just the
PR validation.
> try github actions for PR builds

- .github/workflows/pr.yml
Update github action for PRs to run the license header
and formatting checks as a dedicated action.
> split checks to separate job

- .github/workflows/pr.yml
Reduce duplication by using matrix strategy for multiple
java versions.
> use matrix strategy for build

- .github/workflows/snapshot.yml
- .travis.yml
- project/Bintray.scala
- project/BuildSettings.scala
- project/GitVersion.scala
Adds a workflow to publish snapshots whenever there is
a push to the master branch.
> try out publishing snapshot using actions

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Update names for the secrets used to publish.
> use org secrets for publishing

- iep-lwc-fwding-admin/src/main/resources/application.conf
- iep-lwc-fwding-admin/src/main/resources/log4j2.xml
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Purger.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/PurgerSuite.scala
migrate iep-lwc-fwding-admin to ConfigBinV2
> iep-lwc-fwding-admin: ConfigBinV2 migration

- iep-lwc-fwding-admin/src/main/resources/application.conf
- iep-lwc-fwding-admin/src/main/scala/com/netflix/iep/lwc/fwd/admin/Purger.scala
fix charset typo, causing runtime exception
> fix charset typo, causing runtime exception

- project/Dependencies.scala
> update to scala 2.13.4

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
Keeps track of how many expressions are being evaluated
for forwarding data to LWC API.
> lwc-bridge: add gauge for number of expressions

- project/BuildSettings.scala
When running on a new enough version of Scala or the JDK
use the `--release` flag to target JDK8. Ensures we should
be able to run on JDK8 or newer.
> use `--release` flag on newer JDKs

- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala
add a metric to track tmp files copied to s3
> add a metric to track tmp files copied to s3

- project/Dependencies.scala
Needed to match Atlas libraries.
> use akka 2.6.12

- project/Dependencies.scala
Pull in performance and security fixes.
> use akka 2.6.13 and akka-http 10.2.4

- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/UpdateApiSuite.scala
Add test case to ensure that null char values in the strings
are replaced as expected.
> aggr: ensure null values are replaced

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Update the configbin processing for CloudWatch forwarding
to track how long it has been since the last heartbeat
was received. We have seen a case where somehow the updates
stopped coming and this will make it easy to see and alert
on that sort of failure.
> track time since last heartbeat

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
Ensure if it fails with an exception it will get logged.
> bridge: add log for expr sync stream

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
Update the expression updater so it will automatically
restart the flow to sync the expressions on failures.
> lwc-bridge: restart refresh if it fails

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
Request gzip compressed responses from druid to reduce
the response size that is transferred.
> druid: accept compressed responses

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Applying filters server side can significantly speed up queries.
DimensionFilters are also applied to multi-value dimensions, so we don't need to re-filter locally
and the limits should be unaffected by multi-value dimensions.
> Use TopN query with filters for tags query

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Disable the check for shared names on the smile
factory used by the aggregator. The tag maps have
arbitrary keys and the lookup cost can add up.
> tune options for json factory

- atlas-druid/src/main/resources/application.conf
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
…ntain pre-aggregated metric data
> Ability to optionally normalize rates to support data sources that contain pre-aggregated metric data

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/ExprUpdateService.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/ExprUpdateServiceSuite.scala
Update to handle a compressed response for the expressions
endpoint.
> lwc-bridge: handle compressed response

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/test/scala/com/netflix/atlas/aggregator/AggrConfigSuite.scala
Adjust the config window to spread out the publish requests
over more of the step interval.
> aggr: spread out publishing

- atlas-cloudwatch/src/test/scala/com/netflix/atlas/poller/ClientActorSuite.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/HourlyRollingWriter.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/LocalFilePersistService.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/PersistenceApi.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileFlow.scala
- atlas-persistence/src/main/scala/com/netflix/atlas/persistence/RollingFileWriter.scala
- atlas-persistence/src/test/scala/com/netflix/atlas/persistence/RollingFileWriterSuite.scala
Adapt to updates to the publish payloads.
> update for latest Atlas changes

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/MetricCategory.scala
For metrics with a smaller period, limit the listing to
recently active data. This should help reduce the overhead
and avoid trying to get data for metrics associated with
old resources.
> limit cloudwatch listing to recent data

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
Update listing to follow cache TTL to reduce the overall
number of listing calls performed. The resources we are
polling are typically long lived, so there isn't much
benefit in the higher frequency.
> cloudwatch: reduce frequency of listing

- iep-lwc-bridge/src/main/scala/com/netflix/iep/lwc/BridgeDatapoint.scala
- iep-lwc-bridge/src/test/scala/com/netflix/iep/lwc/BridgeApiSuite.scala
Ensure that tag map used for evaluation matches the id
used for checking the datapoints. Before it should have
been fine because it was only using get, but if the
entrySet was used there could be some odd behavior
because it did not get the deduped length.
> lwc-bridge: use id for tag map

- project/Dependencies.scala
Last version before transition to Spring for DI.
> atlas 1.7.0-rc.26

- project/GitVersion.scala
Prepare for switch to use Spring DI.
> update base version to 0.3.x

- project/Dependencies.scala
Update to latest ASL licensed Akka, Akka-HTTP, Alpakka. Add comment about license change.
> add note about akka versions

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
When the druid type is a histogram, add a statistic dimension to indicate the type. This is used by the UI to determine which operators to show.
> druid: add percentile stat to histograms

- project/BuildSettings.scala
Use `sonatypeOssRepos` instead.
> fix deprecation warning for sonatype

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AkkaPublisher.scala
Update the publisher to use separate client flows for publishing to Atlas and reporting incremental evaluations to LWC. This avoids one getting queued up because of a backlog of requests to the other.
> aggr: separate clients for pub and eval

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/test/resources/application.conf
- atlas-cloudwatch/src/test/resources/test-rules.conf
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessorSuite.scala
- build.sbt
- project/Dependencies.scala
and retrieves data from a Redis cluster.
> Atlas Cloud Watch: Add the Redis cluster metrics processor that stores

- atlas-cloudwatch/src/main/resources/alb.conf
- atlas-cloudwatch/src/main/resources/cloudhsm.conf
- atlas-cloudwatch/src/main/resources/cloudwatch.conf
- atlas-cloudwatch/src/main/resources/dx.conf
- atlas-cloudwatch/src/main/resources/dynamodb.conf
- atlas-cloudwatch/src/main/resources/ec2.conf
- atlas-cloudwatch/src/main/resources/efs.conf
- atlas-cloudwatch/src/main/resources/elasticache.conf
- atlas-cloudwatch/src/main/resources/elb.conf
- atlas-cloudwatch/src/main/resources/es.conf
- atlas-cloudwatch/src/main/resources/events.conf
- atlas-cloudwatch/src/main/resources/firehose.conf
- atlas-cloudwatch/src/main/resources/kinesis.conf
- atlas-cloudwatch/src/main/resources/lambda.conf
- atlas-cloudwatch/src/main/resources/memorydb.conf
- atlas-cloudwatch/src/main/resources/nat-gateway.conf
- atlas-cloudwatch/src/main/resources/neptune.conf
- atlas-cloudwatch/src/main/resources/nlb.conf
- atlas-cloudwatch/src/main/resources/rds.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/resources/route53.conf
- atlas-cloudwatch/src/main/resources/s3-request.conf
- atlas-cloudwatch/src/main/resources/s3.conf
- atlas-cloudwatch/src/main/resources/sns.conf
- atlas-cloudwatch/src/main/resources/sqs.conf
- atlas-cloudwatch/src/main/resources/tgw.conf
Primarily adding offsets to look back at the appropriate time for data.
> Atlas Cloud Watch: Update cloud watch metric configs for streaming.

- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/PublishQueueSuite.scala
> atlas cloudwatch: increase timeout for PublishQueue

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
This is used to filter metrics from the poller.
> atlas cloudwatch: add toTags override for Metrics.

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchDebugger.scala
Captures debugging info from the future poller.
> atlas cloudwatch: add polling debugger method.

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Older versions use a deprecated version of node.
> update github action versions

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/PublishQueue.scala
Record the last successful publish for each queue and the last successful run of the poller.
> atlas cloudwatch: Add last update metrics.

- atlas-aggregator/src/main/resources/application.conf
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AggrConfig.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- project/Dependencies.scala
Enable delayed aggregation of gauge values for the aggregator.
> aggr: try out delayed aggregation

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
The name is matched before creating the druid filter and simplified to `true`. If a query has an or clause where one side is just the name, then it will elide the entire or clause for the filter.
Now it will simplify the query taking into account the name match earlier so only the branch of the or for the particular metric will be present when constructing the filter.
> druid: fix OR query using name

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidClient.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
- atlas-druid/src/test/scala/com/netflix/atlas/druid/DruidDatabaseActorSuite.scala
> druid: fix OR query using name in tags queries

- project/Dependencies.scala
Pull in fix for spin loop in TLSActor.
> akka 2.6.21

- atlas-cloudwatch/src/main/resources/memorydb.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchDebugger.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
> atlas cloudwatch: catch more debug messages.

- atlas-cloudwatch/src/main/resources/ec2.conf
> atlas couldwatch: VPC metrics to 5m delay instead of 4.

- atlas-slotting/src/main/scala/com/netflix/atlas/slotting/SlottingService.scala
Before both crawl instances and crawl ASGs would attempt to update slots if data was available. If both threads run the updateSlots operation at the same time, then it can cause issues including disabling some ASGs.
> slotting: only update slots from the crawl ASG task

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
ConfigBin now has a start message, handle it to avoid noise with it being considered invalid. Also adds some gauges for overall number of configs and data sources.
> lwc-cloudwatch: handle start message

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AppConfiguration.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/AtlasAggregatorService.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PayloadDecoder.scala
- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/UpdateApi.scala
Include endpoint in admin for the aggregates registry. Also add flag to allow dropping data.
> aggr: add admin endpoint for aggregates

- project/Dependencies.scala
Uses older jackson to keep version aligned with atlas libs.
> iep 5.0.21

- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
See if this helps with publishing.
> update to latest sonatype plugin

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/PekkoPublisher.scala
Remove custom class for adjust compression level for gzip output. Use standard helper instead.
> aggr: use gzip helper

- atlas-cloudwatch/src/main/scala/com/netflix/atlas/spring/CloudWatchConfiguration.scala
Adapt PekkoHttpClient usage to recent changes.
> cloudwatch: fix usage of client

- atlas-aggregator/src/main/scala/com/netflix/atlas/aggregator/ShardedAggregatorService.scala
The grouping operator may not provide a list.
> aggr: accept sequence for encode

- atlas-cloudwatch/src/main/resources/mediaconnect.conf
- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
Update poller to consider high resolution metric fast-polling for (Media Live/Connect) specific namespace
> Update poller to consider HRM fast-polling for Media Live/Connect NS

- atlas-cloudwatch/src/main/resources/mediaconnect.conf
- atlas-cloudwatch/src/main/resources/medialive.conf
Moving all of AWS Media Live/Connect category to Polling based HRM with 5s step
> Move all Media Live/Connect NS to Polling based HRM with 5s step

- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Switch to using async client for CloudWatch puts.
> lwc-cloudwatch: use async AWS client

- atlas-stream/src/main/scala/com/netflix/atlas/stream/StreamApi.scala
- iep-lwc-cloudwatch/src/main/scala/com/netflix/iep/lwc/ForwardingService.scala
Remove type params for encode.
> fix compilation issue

- iep-lwc-cloudwatch/src/test/scala/com/netflix/iep/lwc/ForwardingServiceSuite.scala
Update TimeSeriesMessage apply calls in tests.
> lwc-cloudwatch: fix compile error

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Filter out entries that have no data for the summary stats. If they are present it can be misleading and cause issues with operations like topk.
> druid: filter entries with no data

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/spring/CloudWatchConfiguration.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessorSuite.scala
This reverts commit 47b7cf78674828f34930d6bc4e810ad05ef0f604, to allow adding new uri changes first for all regions/env
> Revert "[cw-stream] switch to valkey for read/write both"

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/LocalCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessor.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/RedisClusterCloudWatchMetricsProcessorSuite.scala
- project/Dependencies.scala
use existing redis i/o executionContext for udpateCache to make it async
> Make updateCacheAsync w/ custom redis i/o executionContext

- atlas-cloudwatch/src/main/resources/reference.conf
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchDebugger.scala
- atlas-cloudwatch/src/main/scala/com/netflix/atlas/cloudwatch/CloudWatchPoller.scala
- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
Also fix the name of logged high res points in the debugger.
> atlas cloudwatch: Ask for more data from CW for high res polling.

- atlas-cloudwatch/src/main/resources/mediaconnect.conf
Seeing errant data internally.
> atlas cloudwatch: Set bit rates to sum,rate instead of max.

- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
The count aggregation is passed by to druid, but was getting treated as a single time series and always showing 1. Update to perform a sum of the results returned by druid since the count has already taken place. Also disable rate conversion for the count.
> druid: improve handling of count aggregate

- atlas-cloudwatch/src/main/resources/nat-gateway.conf
https://docs.aws.amazon.com/vpc/latest/userguide/metrics-dimensions-nat-gateway.html
> Add PeakPacketsPerSecond & PeakBytesPerSecond

- atlas-cloudwatch/src/test/scala/com/netflix/atlas/cloudwatch/CloudWatchPollerSuite.scala
- iep-lwc-fwding-admin/src/test/scala/com/netflix/iep/lwc/fwd/admin/ApiSuite.scala
Tweak flakey test cases to try and make the build more reliable.
> update timeouts/ignore flakey tests

- atlas-druid/src/main/scala/com/netflix/atlas/druid/AppConfiguration.scala
- atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidDatabaseActor.scala
Makes it easier to change the injected client for tests.
> druid: create DruidClient as a spring bean

- .github/workflows/release.yml
- project/GitVersion.scala
- project/SonatypeSettings.scala
- project/build.properties
- project/plugins.sbt
Sonatype is phasing out OSSRH so update the publishing to go to the new central portal.
> update to publish to central portal
